# Generated by Django 4.0 on 2022-06-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_move_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Move',
            new_name='Movie',
        ),
    ]
